name: 'SecureQR-Code Generator'
version: 1.0.2
slug: secureqr_code_generator
description: 'Dockerized SecureQR-Code Generator'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
url: 'https://github.com/ChristianScheub/Typescript_Capacitor_SecureQR'
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  HAOS_CONVERTER_PM: apk
webui: 'http://[HOST]:[PORT:5173]/'
ports:
  - 5173/tcp: 5173
