name: 'SecureQR-Code Generator'
version: 1.0.1
slug: secureqr_code_generator
description: 'Dockerized SecureQR-Code Generator'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
webui: 'http://[HOST]:[PORT:5173]/'
ports:
  5173/tcp: 5173
