name: 'HAOS Add-on Converter'
version: 1.2.4
slug: haos_addon_converter
description: 'Web-Converter zum Konvertieren von Docker-Images in Home Assistant Add-ons.'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
url: 'https://github.com/axute/haos-addon-converter'
backup: hot
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  CONVERTER_DATA_DIR: /addons
ingress: true
ingress_port: 80
ingress_stream: false
ingress_entry: /
panel_icon: 'mdi:toy-brick'
panel_title: 'Addon Converter'
map:
  - type: addons
    read_only: false
