name: dockhand
version: 1.0.8
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  SKIP_DF_COLLECTION: 'false'
  DISABLE_LOCAL_LOGIN: 'false'
schema:
  SKIP_DF_COLLECTION: 'str?'
  DISABLE_LOCAL_LOGIN: 'str?'
webui: 'http://[HOST]:[PORT:3000]/'
backup: hot
map:
  - 'share:rw'
ports:
  3000/tcp: 8985
environment:
  DATA_DIR: /data
