name: dockhand
version: 1.0.2
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  SKIP_DF_COLLECTION: 'false'
  DISABLE_LOCAL_LOGIN: 'false'
schema:
  SKIP_DF_COLLECTION: 'str?'
  DISABLE_LOCAL_LOGIN: 'str?'
icon: 'mdi:docker'
ingress: true
ingress_port: 3000
panel_icon: 'mdi:link-variant'
backup: hot
environment:
  DATA_DIR: /data
