name: dockhand
version: 1.0.24
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
tmpfs: false
backup: hot
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  HAOS_CONVERTER_PM: apk
  DATA_DIR: /data
webui: 'http://[HOST]:[PORT:3000]/'
map:
  - type: config
    readOnly: false
options:
  SKIP_DF_COLLECTION: 'false'
  env_vars: []
schema:
  SKIP_DF_COLLECTION: 'str?'
  env_vars:
    - str
