name: dockhand
version: 1.0.21
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
environment:
  DATA_DIR: /data
webui: 'http://[HOST]:[PORT:3000]/'
backup: hot
map:
  - 'config:rw'
ports:
  3000/tcp: 8985
options:
  SKIP_DF_COLLECTION: 'false'
  env_vars: []
schema:
  SKIP_DF_COLLECTION: 'str?'
  env_vars:
    - str
