name: dockhand
version: 0.2.1
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
url: 'https://dockhand.pro/manual/'
tmpfs: true
backup: hot
environment:
  HAOS_CONVERTER_BASHIO_VERSION: 0.17.5
  HAOS_CONVERTER_PM: apk
  DATA_DIR: /data
webui: 'http://[HOST]:[PORT:3000]/'
map:
  - type: config
    read_only: false
options:
  SKIP_DF_COLLECTION: 'false'
  env_vars: []
schema:
  SKIP_DF_COLLECTION: 'str?'
  env_vars:
    - str
