name: dockhand
version: 1.0.5
slug: dockhand
description: 'Portainer Slayer'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  SKIP_DF_COLLECTION: 'false'
  DISABLE_LOCAL_LOGIN: 'false'
schema:
  SKIP_DF_COLLECTION: 'str?'
  DISABLE_LOCAL_LOGIN: 'str?'
panel_port: 3000
backup: hot
ports:
  3000/tcp: 8985
environment:
  DATA_DIR: /data
